FORMAT: 1A
HOST:https://127.0.0.1:8000/sales/api 

# Topic List



## Topic Collection [/topic]

### List All Topics [GET]

+ Response 200 (application/json)

         "count": 0, 
         "next": null, 
         "previous": null, 
         "results": []